### ISSUE TITLE
Where is the v0.3.7-SNAPSHOT?

### ISSUE THREAD

**Issue by conanzxn** [hekailiang/squirrel#35]
It seems there is no label named 0.3.7-SNAPSHOT. Where can I find it?

**Comment by hekailiang** [comment]
https://oss.sonatype.org/content/repositories/snapshots/org/squirrelframework/squirrel-foundation/0.3.7-SNAPSHOT/

If you use maven, make sure the snapshot repository is properly configured, e.g.
<repository>
  <id>sonatype-snapshots</id>
    <url>http://oss.sonatype.org/content/repositories/snapshots/</url>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
</repository>
