### ISSUE TITLE
setDebugEnabled(true) makes machine fail

### ISSUE THREAD

**Issue by jgabrielygalan** [hekailiang/squirrel#38]
I was trying to debug the execution of a state machine, so I enabled the debug mode with setDebugEnabled(true) in the StateMachineConfiguration. The result is an exception when entering the initial state:

16:41:24.186 [main] DEBUG o.s.foundation.fsm.impl.StateImpl - State "initial" entry.
16:41:24.190 [main] DEBUG o.s.f.f.i.AbstractExecutionService - Actions within 'STATE_ENTRY__initial' invoked.
16:41:24.281 [main] ERROR o.s.f.fsm.StateMachineLogger - AuthFlowStateMachine(VQuJQUv3nf): Transition from "initial" to "initial" on "Start" caused exception.
org.squirrelframework.foundation.exception.SquirrelRuntimeException: 00010012 : couldn't invoke 'public abstract void org.squirrelframework.foundation.fsm.StateMachine$TransitionBeginListener.transitionBegin(org.squirrelframework.foundation.fsm.StateMachine$TransitionBeginEvent)' with [org.squirrelframework.foundation.fsm.impl.AbstractStateMachine$TransitionBeginEventImpl@604a550e] on org.squirrelframework.foundation.fsm.impl.AbstractStateMachine$5@19afdb9: null.
	at org.squirrelframework.foundation.util.ReflectUtils.invoke(ReflectUtils.java:337) ~[squirrel-foundation-0.3.0.jar:na]
	at org.squirrelframework.foundation.event.ListenerMethod.invokeMethod(ListenerMethod.java:63) ~[squirrel-foundation-0.3.0.jar:na]
	at org.squirrelframework.foundation.event.PolymEventDispatcher.fireEvent(PolymEventDispatcher.java:68) ~[squirrel-foundation-0.3.0.jar:na]
	at org.squirrelframework.foundation.component.impl.AbstractSubject.fireEvent(AbstractSubject.java:84) ~[squirrel-foundation-0.3.0.jar:na]
	at org.squirrelframework.foundation.fsm.impl.AbstractStateMachine.processEvent(AbstractStateMachine.java:174) ~[squirrel-foundation-0.3.0.jar:na]
	at org.squirrelframework.foundation.fsm.impl.AbstractStateMachine.processEvents(AbstractStateMachine.java:236) ~[squirrel-foundation-0.3.0.jar:na]
	at org.squirrelframework.foundation.fsm.impl.AbstractStateMachine.internalFire(AbstractStateMachine.java:261) ~[squirrel-foundation-0.3.0.jar:na]
	at org.squirrelframework.foundation.fsm.impl.AbstractStateMachine.fire(AbstractStateMachine.java:287) ~[squirrel-foundation-0.3.0.jar:na]

This is the code (it's in a junit test):

		StateMachineBuilder<AuthFlowStateMachine, String, Object, Context> builder = StateMachineBuilderFactory.create(AuthFlowStateMachine.class, String.class, Object.class, Context.class);
		EvaluateAction action = new EvaluateAction();
		action.setArguments("'correct'");
		builder.externalTransition().from("initial").to("second").on(Event.Start).perform(action);
		builder.externalTransition().from("second").to("ok").on("correct");
		AuthFlowStateMachine stateMachine = builder.newStateMachine("initial", StateMachineConfiguration.create().setDebugEnabled(true));
		TokenTransaction transaction = new TokenTransaction();		
		stateMachine.fire(Event.Start, new Context(transaction));
		assertEquals("ok", stateMachine.getCurrentState());

(EvaluateAction evaluates the arguments as an MVEL expression and fires and event of the result as a string, but anyway, it's not even reaching that point).

If I change the above code to setDebugEnabled(false), everything works as expected, and the assertEquals passes.

**Comment by hekailiang** [comment]
It would be helpful if you can provide me a runnable test case to reproduce the issue.

**Comment by jgabrielygalan** [comment]
Yes, sorry, as my state machine, action and context don't do anything relevant, I thought the above was enough. But I have stripped it down to this:

import static org.junit.Assert.assertEquals;
import org.junit.Test;
import org.squirrelframework.foundation.fsm.StateMachineBuilder;
import org.squirrelframework.foundation.fsm.StateMachineBuilderFactory;
import org.squirrelframework.foundation.fsm.StateMachineConfiguration;
import org.squirrelframework.foundation.fsm.impl.AbstractStateMachine;

public class TestSetDebugEnabled {
	@Test
	public void testSetDebugEnabledDoesntBreak() {
		StateMachineBuilder<AuthFlowStateMachine, String, Object, Context> builder = StateMachineBuilderFactory.create(AuthFlowStateMachine.class, String.class, Object.class, Context.class);
		builder.externalTransition().from("initial").to("second").on("Start");
		AuthFlowStateMachine stateMachine = builder.newStateMachine("initial", StateMachineConfiguration.create().setDebugEnabled(true));
		stateMachine.fire("Start", new Context());
		assertEquals("second", stateMachine.getCurrentState());
	}
}
class Context {	
}
class AuthFlowStateMachine extends AbstractStateMachine<AuthFlowStateMachine, String, Object, Context> {	
}

This test fails with the above exception. If I change the true in setDebugEnabled to false, it works.
We are using this dependency configuration:

		<dependency>
			<groupId>org.squirrelframework</groupId>
			<artifactId>squirrel-foundation</artifactId>
			<version>0.3.0</version>
			<exclusions>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-log4j12</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

We needed to strip out he slf4j, since it was interferring with our own logging setup.

**Comment by hekailiang** [comment]
I cannot reproduce the problem with following code and latest version of squirrel. Can you verify the issue against latest version which is 0.3.7.
```java
package org.squirrelframework.foundation.issues;

import static org.junit.Assert.assertEquals;
import org.junit.Test;
import org.squirrelframework.foundation.fsm.StateMachineBuilder;
import org.squirrelframework.foundation.fsm.StateMachineBuilderFactory;
import org.squirrelframework.foundation.fsm.StateMachineConfiguration;
import org.squirrelframework.foundation.fsm.impl.AbstractStateMachine;

/**
 * Created by kailianghe on 1/30/15.
 */
public class Issue38 {
    @Test
    public void testSetDebugEnabledDoesntBreak() {
        StateMachineBuilder<AuthFlowStateMachine, String, Object, Context> builder =
                StateMachineBuilderFactory.create(AuthFlowStateMachine.class, String.class, Object.class, Context.class);

        builder.externalTransition().from("initial").to("second").on("Start");
        AuthFlowStateMachine stateMachine = builder.newStateMachine("initial", StateMachineConfiguration.create().enableDebugMode(true));
        stateMachine.fire("Start", new Context());
        assertEquals("second", stateMachine.getCurrentState());
    }
}

class Context {
}

class AuthFlowStateMachine extends AbstractStateMachine<AuthFlowStateMachine, String, Object, Context> {
}
```

**Comment by jgabrielygalan** [comment]
Yes, it works with version 0.3.7. The method name has changed, so after changing version and method to enableDebugMode, it works. Thanks.
