### ISSUE TITLE
java.util.NoSuchElementException unregistering a TransitionEndListener

### ISSUE THREAD

**Issue by claudio-rosati** [hekailiang/squirrel#40]
Hi,

when I remove a TransitionEndListener previously added to the FSM an exceptionis thrown:

	Please repair it!
	java.util.NoSuchElementException
		at com.google.common.collect.AbstractIterator.next(AbstractIterator.java:154)
		at com.google.common.collect.Iterators.find(Iterators.java:712)
		at 	org.squirrelframework.foundation.event.PolymEventDispatcher.unregister(PolymEventDispatcher.java:47)
		at org.squirrelframework.foundation.component.impl.AbstractSubject.removeListener(AbstractSubject.java:52)
		at org.squirrelframework.foundation.fsm.impl.AbstractStateMachine.removeTransitionEndListener(AbstractStateMachine.java:1234)
		at uk.co.sharp.simulation.modules.block.fsm.FSMEditorPanel.detachListenersToFSM(FSMEditorPanel.java:158)
	...

**Comment by claudio-rosati** [comment]
Here a test case: it's a mixture of my code and your example... but it works throwing the exception.

	import org.squirrelframework.foundation.fsm.StateMachine;
	import org.squirrelframework.foundation.fsm.StateMachineBuilderFactory;
	import org.squirrelframework.foundation.fsm.UntypedStateMachine;
	import org.squirrelframework.foundation.fsm.UntypedStateMachineBuilder;
	import org.squirrelframework.foundation.fsm.annotation.StateMachineParameters;
	import org.squirrelframework.foundation.fsm.impl.AbstractUntypedStateMachine;


	public class QuickStartSample {

		private static final StateMachine.StartListener startListener = e -> started(e);
		private static final StateMachine.StateMachineExceptionListener stateMachineExceptionListener = e -> stateMachineException(e);
		private static final StateMachine.StateMachineListener stateMachineListener = e -> stateMachineEvent(e);
		private static final StateMachine.TransitionBeginListener transitionBeginListener = e -> transitionBegin(e);
		private static final StateMachine.TransitionCompleteListener transitionCompleteListener = e -> transitionComplete(e);
		private static final StateMachine.TransitionDeclinedListener transitionDeclinedListener = e -> transitionDeclined(e);
		private static final StateMachine.TransitionEndListener transitionEndListener = e -> transitionEnd(e);
		private static final StateMachine.TransitionExceptionListener transitionExceptionListener = e -> transitionException(e);

		public static void main ( String[] args ) {

			UntypedStateMachineBuilder builder = StateMachineBuilderFactory.create(StateMachineSample.class);

			builder.externalTransition().from("A").to("B").on(FSMEvent.ToB).callMethod("fromAToB");
			builder.onEntry("B").callMethod("ontoB");

			UntypedStateMachine fsm = builder.newStateMachine("A");

			attachListenersToFSM(fsm);
			fsm.fire(FSMEvent.ToB, 10);
			detachListenersFromFSM(fsm);

			System.out.println("Current state is " + fsm.getCurrentState());

		}

		public static void attachListenersToFSM ( UntypedStateMachine fsm ) {
			fsm.addStartListener(startListener);
			fsm.addStateMachineExceptionListener(stateMachineExceptionListener);
			fsm.addStateMachineListener(stateMachineListener);
			fsm.addTransitionBeginListener(transitionBeginListener);
			fsm.addTransitionCompleteListener(transitionCompleteListener);
			fsm.addTransitionDeclinedListener(transitionDeclinedListener);
			fsm.addTransitionEndListener(transitionEndListener);
			fsm.addTransitionExceptionListener(transitionExceptionListener);
		}

		public static void detachListenersFromFSM ( UntypedStateMachine fsm ) {
			fsm.removeTransitionExceptionListener(transitionExceptionListener);
			fsm.removeTransitionEndListener(transitionEndListener);
			fsm.removeTransitionDecleindListener(transitionDeclinedListener);
			fsm.removeTransitionCompleteListener(transitionCompleteListener);
			fsm.removeTransitionBeginListener(transitionBeginListener);
			fsm.removeStateMachineListener(stateMachineListener);
			fsm.removeStateMachineExceptionListener(stateMachineExceptionListener);
			fsm.removeStartListener(startListener);
		}

		private static void started ( StateMachine.StartEvent e) {
		}

		private static void stateMachineEvent ( StateMachine.StateMachineEvent e) {
		}

		private static void stateMachineException ( StateMachine.StateMachineExceptionEvent e) {
		}

		private static void transitionBegin ( StateMachine.TransitionBeginEvent e) {
		}

		private static void transitionComplete ( StateMachine.TransitionCompleteEvent e) {
		}

		private static void transitionDeclined ( StateMachine.TransitionDeclinedEvent e) {
		}


		private static void transitionEnd (StateMachine.TransitionEndEvent e) {
		}

		private static void transitionException (StateMachine.TransitionExceptionEvent e) {
		}

		@StateMachineParameters( stateType = String.class, eventType = FSMEvent.class, contextType = Integer.class )
		static class StateMachineSample extends AbstractUntypedStateMachine {

			protected void fromAToB ( String from, String to, FSMEvent event, Integer context ) {
				System.out.println("Transition from '" + from + "' to '" + to + "' on event '" + event + "' with context '" + context + "'.");
			}

			protected void ontoB ( String from, String to, FSMEvent event, Integer context ) {
				System.out.println("Entry State \'" + to + "\'.");
			}

		}

		enum FSMEvent {

			ToA, ToB, ToC, ToD

		}

	}

**Comment by hekailiang** [comment]
I just fixed the issue. Please try latest snapshot version.

**Comment by claudio-rosati** [comment]
I've tested the latest snapshot and it is working correctly.
Thank you.
