### ISSUE TITLE
POM creates some problem when building

### ISSUE THREAD

**Issue by claudio-rosati** [hekailiang/squirrel#41]
Here the message related to the problems in POM file:

	Some problems were encountered while building the effective model for org.squirrelframework:squirrel-foundation:bundle:0.3.8-SNAPSHOT
	'build.plugins.plugin.version' for org.apache.felix:maven-bundle-plugin is missing. @ line 155, column 21
	'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing.
	'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing.
	The expression ${pom.artifactId} is deprecated. Please use ${project.artifactId} instead.

	It is highly recommended to fix these problems because they threaten the stability of your build.

	For this reason, future Maven versions might no longer support building such malformed projects.

**Comment by hekailiang** [comment]
Thanks for point out this issue. I just fixed it.
