### ISSUE TITLE
Log exceptions using the logger.

### ISSUE THREAD

**Issue by mahmoudimus** [hekailiang/squirrel#47]
Hi, I noticed this already done in some places (https://github.com/hekailiang/squirrel/commit/5449e81380835a1d18cb559c9ec8bec72e32eef8) where `printStackTrace()` was replaced by a logger statement.

Does it make sense to migrate this change to [`AbstractStateMachine#afterTransitionCausedException`](https://github.com/hekailiang/squirrel/blob/fe2866bf9e0ee0c62b65c38f6209e5496b3cf1ff/squirrel-foundation/src/main/java/org/squirrelframework/foundation/fsm/impl/AbstractStateMachine.java#L388)?

**Comment by hekailiang** [comment]
Yes, i think so. You can try latest snapshot.
