### ISSUE TITLE
Is there a way to get all transitions/events under certain state?

### ISSUE THREAD

**Issue by EasonPai** [hekailiang/squirrel#48]
Is there a way to get all transitions/events under certain state? These data is very important to me.

I have been using Stateless4j, it has a method called getPermittedTriggers().

**Comment by EasonPai** [comment]
Oh, never mind. 

I found method StateMachine.getCurrentRawState().getAcceptableEvents(), this is exactly what I need, thanks!

**Comment by hekailiang** [comment]
Good to know.
