### ISSUE TITLE
Is there a way to dynamically add state and transition to machine?

### ISSUE THREAD

**Issue by EasonPai** [hekailiang/squirrel#49]
If I add states after machine is started, I get exception -- "The state machine builder has been freezed and cannot be changed anymore." 

But in my case, I need to dynamically retrieve data and do some calculation and thus add some new state/transition to machine. So, is there a way to dynamically add state and transition to machine after state machine is started?

**Comment by hekailiang** [comment]
Currently state machine definition will be shared by all the state machine instance. Thus after state machine builder created instance, the state machine definition will be locked and prevented from further changes. 

For the requirement you need, I would suggest enumerate all the possible states when build state machine and dynamically decide which state should be transited to. See the [decision node example](https://github.com/hekailiang/squirrel/blob/master/EXAMPLES.md).

**Comment by EasonPai** [comment]
Thanks for your quick reply.

In my case, it is not likely possible to enumerate all states/transition in advanced, because i allowed user to set transition as a variable which is changeable dynamically. 
I will take a look at the source code of example you provided, hope I can get some learning from it,  thanks again.

**Comment by hekailiang** [comment]
I think you can clone state machine builder through state machine export/import, and then define new transition on the new state machine builder. However, you need to create a new state machine instance and replace the original one. 
```java
UntypedStateMachineBuilder clonedBuilder =
                new UntypedStateMachineImporter().importDefinition(orgFsmInstance.exportXMLDefinition(false));
// add new transition after clone a new state machine builder
clonedBuilder.externalTransition().from("a").to("c").on(TestEvent.toC);
```
I am not sure whether it is a doable solution for you.

**Comment by EasonPai** [comment]
Cool! This looks even closer to what I need, only hope the overhead on performance of  this solution won't be too much. Of course, an official support on this is way awesome. 
I will need some time to give it a try, Thanks!
