### ISSUE TITLE
An unexpected behavior, seems one fire triggers undesired additional transition

### ISSUE THREAD

**Issue by EasonPai** [hekailiang/squirrel#51]
I have an issue, see my testing source below

```java
package squirrel;

import org.squirrelframework.foundation.fsm.StateMachineBuilderFactory;
import org.squirrelframework.foundation.fsm.StateMachineConfiguration;
import org.squirrelframework.foundation.fsm.UntypedStateMachine;
import org.squirrelframework.foundation.fsm.UntypedStateMachineBuilder;
import org.squirrelframework.foundation.fsm.annotation.StateMachineParameters;
import org.squirrelframework.foundation.fsm.impl.AbstractUntypedStateMachine;

public class TestingTransition {
	private static UntypedStateMachineBuilder mBuilder;
    public static void main(String[] args) {
    	
        mBuilder = StateMachineBuilderFactory.create(UntypedStateMachineSample.class);
        
        mBuilder.externalTransition().from("A").to("B").on("A2B").callMethod("enter");
        mBuilder.externalTransition().from("B").to("C").on("B2C").callMethod("enter");
        mBuilder.externalTransition().from("C").to("D").on("C2D").callMethod("enter");
        
        UntypedStateMachine fsm = mBuilder.newStateMachine("A", StateMachineConfiguration.create().enableDebugMode(true));
        
        fsm.start();
        fsm.fire("A2B");
    }
    
    @StateMachineParameters(stateType=String.class, eventType=String.class, contextType=Integer.class)
    static class UntypedStateMachineSample extends AbstractUntypedStateMachine {
    	protected void enter(String from, String to, String event, Integer context) {
        	System.out.println("[enter] Transition from '"+from+"' to '"+to+"' on event '"+event+
        			"' CurrentState ('"+getCurrentState()+"').");
        	if(getCurrentState().equals("A")){
        		fire("A2B", 0);
        	}
        	if(getCurrentState().equals("B")){
        		fire("B2C", 0);
        	}
        	if(getCurrentState().equals("C")){
        		fire("C2D", 0);
        	}
        }
    }
}
```

run it, and I get

> INFO [main] - UntypedStateMachineSample(IBErRXlwTM): Transition from "A" on "A2B" with context "null" begin.
> INFO [main]- Before execute method call action "enter:0" (1 of 1).
> [enter] Transition from 'A' to 'B' on event 'A2B' CurrentState ('A').
> INFO [main] - After execute method call action "enter:0" which took 7.364 ms.
> INFO [main] - (IBErRXlwTM): Transition from "A" to "B" on "A2B" complete which took 22.29 ms.
> INFO [main]  -(IBErRXlwTM): Transition from "B" on "A2B" with context "0" begin.
> WARN [main]- (IBErRXlwTM): Transition from "B" on "A2B" declined.

(To make it more readable in github UI, I have trimmed some less critical letters from the original output)

The issue here is that when 
> "Transition from "A" to "B" on "A2B" complete..." 

is done,  I didn't trigger anything, but I continue to get output 
> Transition from "B" on "A2B" with context "0" begin.

Also, from my source code you can see that there is no such trigger exists.

**Comment by hekailiang** [comment]
It is not unexpected behavior. Actually, it is expected. In your enter method your fired event "A2B" when current state is "A". First "A2B" is fired in your main method, and second is in your enter method.
