### ISSUE TITLE
Events with parameters?

### ISSUE THREAD

**Issue by jordillonch** [hekailiang/squirrel#55]
Is there some way of use events that bring some parameters?
All examples that I found in the code are just events that are enums.
Thanks!

**Comment by hekailiang** [comment]
What do you mean events bring some parameters? Could you give me an example and let me know why you need this?

**Comment by jordillonch** [comment]
I mean to carry some data with the event. For example I am thinking in an event like "join player" and I would like to get the "player id" from the event.

**Comment by hekailiang** [comment]
I think you can put this kind of parameters in Context object, which means fire an event like "JOIN_PLAYER" with context "player_id".

**Comment by jordillonch** [comment]
Yes but I want to use the context as a game state as it is done in your snake example.

**Comment by hekailiang** [comment]
Then you can compose a game state and the parameter as the Context object.

**Comment by jordillonch** [comment]
Yes, I see. But I think may be it's more clear to put data related with the event in the same even.
Anyway, thanks for your answers 😀
