### ISSUE TITLE
Load state machine definition from file

### ISSUE THREAD

**Issue by ichsteffen** [hekailiang/squirrel#62]
Hi,

I would like to know if there is any why to load a state machine definition out of a file (or any other resource).

I have found the SCXMLVisitor to save a state machine defintion to SCXML. But I could not find any thing like an SCXML loader. It there one?

Best regards,

Steffen

**Comment by ichsteffen** [comment]
Please ignore my question. RTFM ;)

> **UntypedStateMachineImporter** can be used to import state machine SCXML-similar definition which was exported by SCXMLVisitor or handwriting definition.

Thank´s anyway.

**Comment by shub124** [comment]
@ichsteffen Can you please let me know how to read an scxml file and have the scxmldef object to be passed to UntypedStateMachineImporter?
