### ISSUE TITLE
请问状态之间的转化过程中的业务代码应该写在哪里

### ISSUE THREAD

**Issue by 3070190** [hekailiang/squirrel#69]
您好，我最近在学习有限状态机模式，看到您写的框架很开心，但是由于水平有限，不能够完全理解框架的功能。比如：当我定义了状态A和状态B，和转换事件AToB，那事件AToB中对应的业务代码要写在哪里呢，看到 Issue40 在代码中的例子是写在状态机的内部的 （fromAToB 方法和 ontoB 方法），不知道是不是应该这么用。希望能够得到您的回答，谢谢

**Comment by hekailiang** [comment]
业务逻辑可以写在transion的方法中, state进入/离开的方法中, 看具体的需求
