### ISSUE TITLE
请问怎么集成到spring中?

### ISSUE THREAD

**Issue by flyingbread** [hekailiang/squirrel#71]
转换方法中要通过service方法完成数据持久化

**Comment by TimGuan** [comment]
http://www.timguan.net/2017/06/21/squirrel-foundation%E7%8A%B6%E6%80%81%E6%9C%BA%E7%9A%84%E4%BD%BF%E7%94%A8%E7%BB%86%E8%8A%82/

**Comment by hekailiang** [comment]
@TimGuan 感谢分享，我希望可以把这篇文章加到首页使用案例介绍上，你觉得可以吗？

**Comment by TimGuan** [comment]
可以，如果你觉得合适的话~

**Comment by Angry-Rabbit** [comment]
> 
> 
> @flyingbread [squirrel-foundation状态机的使用细节](http://www.timguan.net/2017/06/21/squirrel-foundation%E7%8A%B6%E6%80%81%E6%9C%BA%E7%9A%84%E4%BD%BF%E7%94%A8%E7%BB%86%E8%8A%82/)

网站停止服务了吗

**Comment by hekailiang** [comment]
https://segmentfault.com/a/1190000009906469

**Comment by hekailiang** [comment]
参见[Example](https://github.com/hekailiang/squirrel/blob/master/EXAMPLES.md)中的StateMachineAutowireProcessor
