### ISSUE TITLE
这么好的工具不更新了吗

### ISSUE THREAD

**Issue by xiaosazixian** [hekailiang/squirrel#76]
我看代码还有在提交。但是没有出版本了。现在正在比较spring statemachine和squirrel，本来想选squirrel。

**Comment by doukai** [comment]
是啊，好可惜啊

**Comment by hekailiang** [comment]
谢谢关注！因为功能都已经完整，而且在一些项目上运行稳定。没有特别的需求，暂时不会改动了。如果有需要订制的能力，可以fork一个分支自行维护。
