### ISSUE TITLE
StateMachine.start的一个小问题

### ISSUE THREAD

**Issue by SuperNoobTao** [hekailiang/squirrel#83]
额，有一点不太明白，
我在ExtensionMethodCallTest中把start()注释了，因为文档里说是状态机默认自启动的。
但是，注释之后报了错：
![Uploading image.png…]()

请问这是为什么呢？我仅仅是把手动启动改成状态机默认自启动，它的行为就不一样了。

**Comment by hekailiang** [comment]
start()默认context为null，直接autoStart时，会使用fire event时的context作为state machine的启动上下文

**Comment by SuperNoobTao** [comment]
好的，谢谢作者大大
