### ISSUE TITLE
Identifier for a machine is setting initial state in `prePostConstruct`

### ISSUE THREAD

**Issue by apoorvprecisely** [hekailiang/squirrel#91]
https://github.com/hekailiang/squirrel/blob/ebf54bf4be104f6750082ccf893d4a1106ab4b89/squirrel-foundation/src/main/java/org/squirrelframework/foundation/fsm/impl/AbstractStateMachine.java#L106

In a scenario where you implement `StateMachineData.Reader` for persistence you'll require setting an identifier before you set initial state

**Comment by hekailiang** [comment]
thx!
