### ISSUE TITLE
异常怎么往外抛出

### ISSUE THREAD

**Issue by lycaste** [hekailiang/squirrel#94]
自定义的异常 全部被SquirrelRuntimeException 给吃掉，然后SquirrelRuntimeException抛给了前端。我怎么能把自定义异常丢出去

**Comment by hekailiang** [comment]
你可以看下“Transition Exception Handling“这一部分文档

**Comment by lycaste** [comment]
谢谢

**Comment by DropOfJupiter** [comment]
为何我重写了com.aiya.kpy.ordct.fsm.OrderChargeBackStateMachine#afterTransitionCausedException 却进不来该方法。。。
